AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - stg
      - prod
    Description: Environment name
  AVDefinitionS3Bucket:
    Type: String
    Default: ""
    Description: S3 bucket for ClamAV definitions. Leave empty to create one.

Conditions:
  CreateDefinitionBucket: !Equals [!Ref AVDefinitionS3Bucket, ""]

Resources:
  AVScanQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "av-scan-queue-dlq-${Environment}"
      MessageRetentionPeriod: 1209600
      RedriveAllowPolicy: '{"redrivePermission":"allowAll"}'

  AVEventBridgeDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "av-eventbridge-dlq-${Environment}"
      MessageRetentionPeriod: 1209600

  AVScanQueue:
    Type: AWS::SQS::Queue
    DependsOn: AVScanQueueDLQ
    Properties:
      QueueName: !Sub "av-scan-queue-${Environment}"
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        Fn::Sub:
          - '{"deadLetterTargetArn":"${Arn}","maxReceiveCount":5}'
          - Arn: !GetAtt AVScanQueueDLQ.Arn

  AVDefinitionBucket:
    Type: AWS::S3::Bucket
    Condition: CreateDefinitionBucket
    Properties:
      BucketName: !Sub "av-definitions-${AWS::AccountId}-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AVScanEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "av-scan-s3-object-created-${Environment}"
      Description: S3 Object Created events for AV scan queue (keys matching */ecgfile/*)
      EventPattern:
        source: ["aws.s3"]
        detail-type: ["Object Created"]
        detail:
          object:
            key: [{ wildcard: "*/ecgfile/*" }]
      State: ENABLED
      Targets:
        - Arn: !GetAtt AVScanQueue.Arn
          Id: AVScanQueue
          DeadLetterConfig:
            Arn: !GetAtt AVEventBridgeDLQ.Arn

  AVScanQueueEventBridgePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AVScanQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt AVScanEventBridgeRule.Arn
      Queues:
        - !Ref AVScanQueue

  AVEventBridgeDLQPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AVEventBridgeDLQ.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt AVScanEventBridgeRule.Arn
      Queues:
        - !Ref AVEventBridgeDLQ

Outputs:
  AVScanQueueUrl:
    Description: SQS queue URL for scan jobs
    Value: !Ref AVScanQueue
    Export:
      Name: !Sub "bucket-antivirus-lambdas-${Environment}-AVScanQueueUrl"
  AVScanQueueArn:
    Description: SQS queue ARN for scan jobs
    Value: !GetAtt AVScanQueue.Arn
    Export:
      Name: !Sub "bucket-antivirus-lambdas-${Environment}-AVScanQueueArn"
  AVScanQueueDLQUrl:
    Description: DLQ for failed scan messages
    Value: !Ref AVScanQueueDLQ
  AVEventBridgeDLQUrl:
    Description: DLQ for EventBridge failed deliveries
    Value: !Ref AVEventBridgeDLQ
  AVDefinitionBucketName:
    Description: S3 bucket for ClamAV definitions
    Value: !If
      - CreateDefinitionBucket
      - !Ref AVDefinitionBucket
      - !Ref AVDefinitionS3Bucket
    Export:
      Name: !Sub "bucket-antivirus-lambdas-${Environment}-AVDefinitionBucketName"
